# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63dca25d8c38a509fada26b71c2e02a25144a0cfa58d8ba09e965c978e8fcf628ede8c5ac8132bdf6ee664434d0c959f7e0c2eb29a4e9c60f9c7afa7eefc9eaa

test:
  secret_key_base: 862c263fc39975a2cca85fd90ea0b59bcb8c244157782d2b3cfbbe2e0e27f9e23fc00d7d85cf0decc883d5a10b61bd517deaf00340a490454aeb1f7d444fe251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
